import Head from "next/head";

export default function ContactPage() {
  return (
    <div className='container main'>
        {/* <Head>
          <title>Contact</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head> */}
        <h1>Contact</h1>
        <p>This is the contact page.</p>
        <a href='/' className='back-link'>Back to Home</a>
        

      
    </div>
  )
}
