import Head from "next/head";




export default function Home() {
  return (
    <>
      <Head>
        <title>Fake Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container main">
        <h2>Fake Store</h2>
      </div>
    </>
  );
}
